<?php

namespace Database\Seeders;

use App\Models\LabTestDefinition;
use Illuminate\Database\Seeder;

class LabTestDefinitionSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'test_code' => 'URE',
                'test_name' => 'Ure',
                'test_name_normalized' => 'ure',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'mmol/L',
                'male_reference_min' => 2.5,
                'male_reference_max' => 7.5,
                'male_reference_text' => '2.5 - 7.5',
                'female_reference_min' => 2.5,
                'female_reference_max' => 7.5,
                'female_reference_text' => '2.5 - 7.5',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'GLU',
                'test_name' => 'Glucose',
                'test_name_normalized' => 'glucose',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'mmol/L',
                'male_reference_min' => 4.1,
                'male_reference_max' => 5.9,
                'male_reference_text' => '4.1 - 5.9',
                'female_reference_min' => 4.1,
                'female_reference_max' => 5.9,
                'female_reference_text' => '4.1 - 5.9',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'CREA',
                'test_name' => 'Creatinin',
                'test_name_normalized' => 'creatinin',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'µmol/L',
                'male_reference_min' => 45,
                'male_reference_max' => 120,
                'male_reference_text' => '45 - 120',
                'female_reference_min' => 45,
                'female_reference_max' => 120,
                'female_reference_text' => '45 - 120',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'URIC',
                'test_name' => 'Acid Uric',
                'test_name_normalized' => 'acid uric',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'µmol/L',
                'male_reference_min' => 120,
                'male_reference_max' => 380,
                'male_reference_text' => '120 - 380',
                'female_reference_min' => 120,
                'female_reference_max' => 380,
                'female_reference_text' => '120 - 380',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'TP',
                'test_name' => 'Protein T.P',
                'test_name_normalized' => 'protein tp',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'g/L',
                'male_reference_min' => 60,
                'male_reference_max' => 82,
                'male_reference_text' => '60 - 82',
                'female_reference_min' => 60,
                'female_reference_max' => 82,
                'female_reference_text' => '60 - 82',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'ALB',
                'test_name' => 'Albumin',
                'test_name_normalized' => 'albumin',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'g/L',
                'male_reference_min' => 35,
                'male_reference_max' => 52,
                'male_reference_text' => '35 - 52',
                'female_reference_min' => 35,
                'female_reference_max' => 52,
                'female_reference_text' => '35 - 52',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'CHOL',
                'test_name' => 'Cholesterol',
                'test_name_normalized' => 'cholesterol',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'mmol/L',
                'male_reference_min' => 3.6,
                'male_reference_max' => 5.2,
                'male_reference_text' => '3.6 - 5.2',
                'female_reference_min' => 3.6,
                'female_reference_max' => 5.2,
                'female_reference_text' => '3.6 - 5.2',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'TRIG',
                'test_name' => 'Triglycerid',
                'test_name_normalized' => 'triglycerid',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'mmol/L',
                'male_reference_min' => 0.46,
                'male_reference_max' => 1.88,
                'male_reference_text' => '0.46 - 1.88',
                'female_reference_min' => 0.46,
                'female_reference_max' => 1.88,
                'female_reference_text' => '0.46 - 1.88',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'AST',
                'test_name' => 'AST (GOT)',
                'test_name_normalized' => 'ast got',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'U/L',
                'male_reference_min' => null,
                'male_reference_max' => 37,
                'male_reference_text' => '<= 37',
                'female_reference_min' => null,
                'female_reference_max' => 37,
                'female_reference_text' => '<= 37',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'ALT',
                'test_name' => 'ALT (GPT)',
                'test_name_normalized' => 'alt gpt',
                'panel_type' => 'blood',
                'sample_group' => 'biochemistry',
                'standard_unit' => 'U/L',
                'male_reference_min' => null,
                'male_reference_max' => 40,
                'male_reference_text' => '< 40',
                'female_reference_min' => null,
                'female_reference_max' => 40,
                'female_reference_text' => '< 40',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'NA',
                'test_name' => 'Na+',
                'test_name_normalized' => 'na',
                'panel_type' => 'blood',
                'sample_group' => 'electrolyte',
                'standard_unit' => 'mmol/L',
                'male_reference_min' => 135,
                'male_reference_max' => 145,
                'male_reference_text' => '135 - 145',
                'female_reference_min' => 135,
                'female_reference_max' => 145,
                'female_reference_text' => '135 - 145',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'K',
                'test_name' => 'K+',
                'test_name_normalized' => 'k',
                'panel_type' => 'blood',
                'sample_group' => 'electrolyte',
                'standard_unit' => 'mmol/L',
                'male_reference_min' => 3.5,
                'male_reference_max' => 5.0,
                'male_reference_text' => '3.5 - 5.0',
                'female_reference_min' => 3.5,
                'female_reference_max' => 5.0,
                'female_reference_text' => '3.5 - 5.0',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'CL',
                'test_name' => 'Cl-',
                'test_name_normalized' => 'cl',
                'panel_type' => 'blood',
                'sample_group' => 'electrolyte',
                'standard_unit' => 'mmol/L',
                'male_reference_min' => 98,
                'male_reference_max' => 106,
                'male_reference_text' => '98 - 106',
                'female_reference_min' => 98,
                'female_reference_max' => 106,
                'female_reference_text' => '98 - 106',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'WBC',
                'test_name' => 'Số lượng bạch cầu (WBC)',
                'test_name_normalized' => 'wbc',
                'panel_type' => 'blood',
                'sample_group' => 'hematology',
                'standard_unit' => '10^9/L',
                'male_reference_min' => 4.0,
                'male_reference_max' => 10.0,
                'male_reference_text' => '4.0 - 10',
                'female_reference_min' => 4.0,
                'female_reference_max' => 10.0,
                'female_reference_text' => '4.0 - 10',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'RBC',
                'test_name' => 'Số lượng hồng cầu (RBC)',
                'test_name_normalized' => 'rbc',
                'panel_type' => 'blood',
                'sample_group' => 'hematology',
                'standard_unit' => '10^12/L',
                'male_reference_min' => 3.50,
                'male_reference_max' => 5.60,
                'male_reference_text' => '3.50 - 5.60',
                'female_reference_min' => 3.50,
                'female_reference_max' => 5.60,
                'female_reference_text' => '3.50 - 5.60',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'HGB',
                'test_name' => 'Huyết sắc tố (HGB)',
                'test_name_normalized' => 'hgb',
                'panel_type' => 'blood',
                'sample_group' => 'hematology',
                'standard_unit' => 'g/L',
                'male_reference_min' => 110,
                'male_reference_max' => 160,
                'male_reference_text' => '110 - 160',
                'female_reference_min' => 110,
                'female_reference_max' => 160,
                'female_reference_text' => '110 - 160',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'LEU',
                'test_name' => 'Bạch cầu',
                'test_name_normalized' => 'bach cau urine',
                'panel_type' => 'urine',
                'sample_group' => 'urine',
                'standard_unit' => 'Leu/ul',
                'male_reference_min' => null,
                'male_reference_max' => null,
                'male_reference_text' => 'Âm tính',
                'female_reference_min' => null,
                'female_reference_max' => null,
                'female_reference_text' => 'Âm tính',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'NIT',
                'test_name' => 'Nitrit',
                'test_name_normalized' => 'nitrit',
                'panel_type' => 'urine',
                'sample_group' => 'urine',
                'standard_unit' => null,
                'male_reference_min' => null,
                'male_reference_max' => null,
                'male_reference_text' => 'Âm tính',
                'female_reference_min' => null,
                'female_reference_max' => null,
                'female_reference_text' => 'Âm tính',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'PH',
                'test_name' => 'pH',
                'test_name_normalized' => 'ph',
                'panel_type' => 'urine',
                'sample_group' => 'urine',
                'standard_unit' => null,
                'male_reference_min' => 5.0,
                'male_reference_max' => 7.0,
                'male_reference_text' => '5.0 - 7.0',
                'female_reference_min' => 5.0,
                'female_reference_max' => 7.0,
                'female_reference_text' => '5.0 - 7.0',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
            [
                'test_code' => 'SG',
                'test_name' => 'SG',
                'test_name_normalized' => 'sg',
                'panel_type' => 'urine',
                'sample_group' => 'urine',
                'standard_unit' => null,
                'male_reference_min' => 1.0030,
                'male_reference_max' => 1.0350,
                'male_reference_text' => '1.003 - 1.035',
                'female_reference_min' => 1.0030,
                'female_reference_max' => 1.0350,
                'female_reference_text' => '1.003 - 1.035',
                'default_price' => 0,
                'default_include_in_billing' => true,
                'is_active' => true,
            ],
        ];

        foreach ($items as $item) {
            LabTestDefinition::updateOrCreate(
                ['test_code' => $item['test_code']],
                $item
            );
        }
    }
}
